version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn test
workflows:
    test:
      jobs:
        - test
